INTERN_REQUEST_TYPE = "request"
INTERN_MESSAGE_ID = "messageid"
INTERN_MESSAGE_PAYLOAD = "payload"

REQ_ACTION_LIST = "listActions"

REQ_DEVICE_LIST = "listDevices"

REQ_PROFILE_SET = "getProfileSet"
REQ_PROFILE_SET_PARAM_DEVICE = "deviceID"